config/routes.rb
Rails.application.routes.draw do

#read all
get "tasks", to: "tasks#index", as:'tasks'

# create
get "tasks/new", to: "tasks#new", as: 'new_task'
post "tasks", to: "tasks#create"

#read a restaurant
get "tasks/:id", to: "tasks#show", as: 'task'
# tasks/1 => params[:id] => 1
# tasks/show => params[:id] => "show"

# update a task
get "tasks/:id/edit", to: "tasks#edit", as: 'edit_task'
patch "tasks/:id", to: "tasks#update"

#delete
delete "tasks/:id", to: "tasks#destroy", as: 'delete'

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



# GET '/tasks/:id': get a precise task, e.g GET '/tasks/3' get task with id=3
# GET '/tasks/new': get the form to create a new task
# POST '/tasks': post a new task
# GET '/tasks/:id/edit': get the form to edit an existing task
# PATCH '/tasks/:id': update an existing task
# DELETE '/tasks/:id': delete an existing task

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def update
      @task.update(task_params)
      redirect_to task_path(@task)
    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

private

  def task_params

  params.require(:task).permit(:name, :description, :done)

  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div>

<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= label_tag(:done, "Check if status is") %>
  <%= f.check_box :done %>
  <%= f.submit class: 'btn btn-primary'%>
<% end %>

</div>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>


<%  @tasks.each do |task_object| %>
<div>
<p><%=  task_object.name %></p>
<%=  task_object.description %>
<%=  task_object.done %>
<%=  task_object.createdat%>
<p><%= link_to task_object.name, task_path(task_object) %></p>
<%= link_to "Delete", delete_path(task_object),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
</div>
<% end %>


<!-- a link to its show view (use a link_to helper)
a link to its edit view
a link to its delete action. Hint: a standard link does not allow to perform DELETE request, so here you should add a method: :delete option to your link_to helper. -->

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<h2><%= @task.description %></h2>
<h2><%= @task.createdat %></h2>
<p><%= @task.done %></p>